# Q2
# What are the events that have more than one factuality value annotation?

prefix oa: <http://www.w3.org/ns/oa#>
prefix nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#>
prefix pvcp: <https://w3id.org/provcorp/np/public/vocab/general/>
prefix pvcpf: <https://w3id.org/provcorp/np/public/vocab/factbank/>


SELECT ?event ?eID ?event_word (count(?fv) as ?fv_count)
WHERE {
?event pvcpf:hasEID ?eID;
oa:hasTarget ?offset.
?fv pvcpf:hasTargetEvent ?event.
?offset nif:anchorOf ?event_word.
}
GROUP BY ?event ?eID ?event_word
HAVING (count(?fv) > 1)
