# Q3
# What are the different factuality values expressed per document, and which values appear the most?


prefix pvcpf: <https://w3id.org/provcorp/np/public/vocab/factbank/>
prefix pvcp: <https://w3id.org/provcorp/np/public/vocab/general/>
prefix oa: <http://www.w3.org/ns/oa#>

select ?text (group_concat(?fv;separator=",") as ?annotated_fvs)
where
{
select ?text ?fv (count(?fv) as ?count)
WHERE {
     ?anno pvcpf:hasFactvalue ?fv.      # data from FV fact value np
     ?anno pvcpf:hasTargetEvent ?e.     # data from FV fact value np
     ?e oa:hasTarget ?offset.           # data from FV event np
     ?offset pvcp:isPartOfText ?text.  # data from word np
}
order by desc(?count)
}
