# Q4
# Which events are annotated with different factuality values? And how many times is that event annotated with a certain factuality value?

prefix pvcpf: <https://w3id.org/provcorp/np/public/vocab/factbank/>
prefix pvcp: <https://w3id.org/provcorp/np/public/vocab/general/>
prefix oa: <http://www.w3.org/ns/oa#>
prefix nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#>

SELECT ?text ?event ?fv (count(?fv) as ?count)
WHERE {
     ?anno pvcpf:hasFactvalue ?fv.      # data from FV fact value np
     ?anno pvcpf:hasTargetEvent ?e.     # data from FV fact value np
     ?e oa:hasTarget ?offset.           # data from FV event np
     ?offset pvcp:isPartOfText ?text.  # data from word np
     ?offset nif:anchorOf ?event.
}
