# Q5
# Counts for certain annotation values.

# Fact Value Count
# We could look at this info on a document level by specifying a specific document (uncomment the hashed lines)

prefix pvcpf: <https://w3id.org/provcorp/np/public/vocab/factbank/>
prefix pvcp: <https://w3id.org/provcorp/np/public/vocab/general/>
prefix oa: <http://www.w3.org/ns/oa#>

SELECT ?fv (count(?fv) as ?count)
WHERE {
     ?anno pvcpf:hasFactvalue ?fv.
     #?anno pvcpf:hasTargetEvent ?e.
     #?e oa:hasTarget ?offset.
     #?offset pvcp:isPartOfText <https://w3id.org/provcorp/np/protected/text/wsj_0106.RANkA5vcpEBTWNjdi6GELsfrgazGJzmwbzc4UiMfy7B68#text>.
}
ORDER BY DESC(?count)




# Source Count

prefix pvcpf: <https://w3id.org/provcorp/np/public/vocab/factbank/>
SELECT ?text (count(?text) as ?count)
WHERE {
     ?source pvcpf:hasSourceText ?text.
}
ORDER BY DESC(?count)




# Event Count

prefix pvcpf: <https://w3id.org/provcorp/np/public/vocab/factbank/>
select (count(?event) as ?count)
where{

     ?event pvcpf:hasEID ?id.
}




# POS tags Count

prefix olia: <http://purl.org/olia/sfb632.owl#>
SELECT ?pos (count(?pos) as ?count)
WHERE
{
   ?s <http://purl.org/olia/sfb632.owl#POS> ?pos
}
ORDER BY DESC(?count)




# Count the amount of events per a specific attribution

prefix pvcpp: <https://w3id.org/provcorp/np/public/vocab/parc/>
prefix pvcpf: <https://w3id.org/provcorp/np/public/vocab/factbank/>
prefix oa: <http://www.w3.org/ns/oa#>
prefix nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#>
select ?Predicate (count(distinct ?offset) as ?Count)
where {
     ?event pvcpf:hasEID ?eid.
     ?event oa:hasTarget ?offset.
     ?panno ?Predicate ?offset.
     ?offset nif:anchorOf ?literal.
     VALUES ?Predicate { pvcpp:hasContentAnnotatedWord pvcpp:hasCueAnnotatedWord pvcpp:hasSourceAnnotatedWord }.


 }
group by ?Predicate
