# Which events are a source attribution?
# To find events that are are Content or Cue attribution, change pvcpp:hasSourceAnnotatedWord to pvcpp:hasContentAnnotatedWord or pvcpp:hasCueAnnotatedWord.

prefix pvcpp: <https://w3id.org/provcorp/np/public/vocab/parc/>
prefix pvcpf: <https://w3id.org/provcorp/np/public/vocab/factbank/>
prefix oa: <http://www.w3.org/ns/oa#>
prefix nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#>

 select ?event ?eid ?offset ?panno ?literal
 where {
     ?event pvcpf:hasEID ?eid.
     ?event oa:hasTarget ?offset.
     ?panno pvcpp:hasSourceAnnotatedWord ?offset.
     ?offset nif:anchorOf ?literal.

  }
 order by ?eid
