# L2
# Return all events that have more than one fact value annotation. 

prefix pvcpf: <https://w3id.org/provcorp/vocab/factbank/>
prefix oa: <http://www.w3.org/ns/oa#>
prefix nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#>
prefix pvcp: <https://w3id.org/provcorp/vocab/general/>


SELECT ?eID ?event_word (count(?fv) as ?fv_count) ?text
WHERE {
    ?event pvcpf:hasEID ?eID;
           oa:hasTarget ?offset.
    ?fv pvcpf:hasTargetEvent ?event.
    ?offset nif:anchorOf ?event_word; pvcp:isPartOfText ?text.
}
GROUP BY ?text ?eID ?event_word
HAVING (count(?fv) > 1)
