# L3

# What are the different beliefs expressed in a document?
# (For all files. Returns the fact values of a file, presented in order of descending count.)

prefix pvcpf: <https://w3id.org/provcorp/vocab/factbank/>
prefix pvcp: <https://w3id.org/provcorp/vocab/general/>
prefix oa: <http://www.w3.org/ns/oa#>

select ?filename (group_concat(?fv;separator=",") as ?annotated_fvs)
where
{
select ?filename ?fv (count(?fv) as ?count)
WHERE {
     ?anno pvcpf:hasFactvalue ?fv.      # data from FV fact value np
     ?anno pvcpf:hasTargetEvent ?e.     # data from FV fact value np
     ?e oa:hasTarget ?offset.           # data from FV event np
     ?offset pvcp:isPartOfText ?text.  # data from word np
     bind(str(?text) as ?textstr).
     bind(strbefore(?textstr,'.R') as ?str1).
     bind(substr(?str1, 45) as ?filename).
}
order by desc(?count)
}
