
#L4
# What is the certainty of an event? Does an event ever have different certainty values?
# (How many times does an event get a certain fact value? does it ever get a different fact value?)

prefix pvcpf: <https://w3id.org/provcorp/vocab/factbank/>
prefix pvcp: <https://w3id.org/provcorp/vocab/general/>
prefix oa: <http://www.w3.org/ns/oa#>
prefix nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#>

SELECT ?filename ?event ?fv (count(?fv) as ?count)
WHERE {
     ?anno pvcpf:hasFactvalue ?fv.      # data from FV fact value np
     ?anno pvcpf:hasTargetEvent ?e.     # data from FV fact value np
     ?e oa:hasTarget ?offset.           # data from FV event np
     ?offset pvcp:isPartOfText ?text.  # data from word np
     ?offset nif:anchorOf ?event.
     bind(str(?text) as ?textstr).
     bind(strbefore(?textstr,'.R') as ?str1).
     bind(substr(?str1, 45) as ?filename).
}
