# Return events that are a SOURCE attribution.
# To find events that are are Content or Cue attribution, change pvcpp:hasSourceAnnotatedWord to pvcpp:hasContentAnnotatedWord or pvcpp:hasCueAnnotatedWord.

 prefix pvcpp: <https://w3id.org/provcorp/vocab/parc/>
 prefix pvcpf: <https://w3id.org/provcorp/vocab/factbank/>
 prefix oa: <http://www.w3.org/ns/oa#>
 prefix nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#>

 select ?filename ?eid ?Offset ?panno ?literal
 where {
     ?event pvcpf:hasEID ?eid.
     ?event oa:hasTarget ?offset.
     ?panno pvcpp:hasSourceAnnotatedWord ?offset.
     ?offset nif:anchorOf ?literal.

      bind(str(?event) as ?event_str).
      bind(strbefore(?event_str,'.R') as ?str1).
      bind(substr(?str1, 60, 8) as ?filename).

      bind(str(?offset) as ?offset_str).
      bind(substr(?offset_str,106) as ?Offset).
  }
 order by ?eid
